### ISSUE TITLE
QWidget isMaximized() returns 'true' and 'false'

### ISSUE THREAD

**Issue by giumas** [PySide/PySide#124]
Using PySide 1.2.2, when I try to save the app settings, I noticed that the function in object returns 'true' and 'false' rather than True and False. Is this a bug?

**Comment by jdreaver** [comment]
Are you sure that this is the case? Here is a test program:

```python
from PySide import QtGui
import sys

app = QtGui.QApplication(sys.argv)

widget = QtGui.QWidget()
widget.show()
print(widget.isMaximized(), type(widget.isMaximized()))

sys.exit(app.exec_())
```

When I run it, I get the following output:

```
False <class 'bool'>
```

When you save settings using `QSettings`, indeed the settings are saved as strings. I don't think this is a bug. I think that settings are saved in flat text files in Linux, or in the Windows registry, so there is no notion of a type besides strings (bool, int, etc).

**Comment by giumas** [comment]
I switched from `isMaximized()` to `isFullScreen()`, and it works using these helper functions:

    def _load_view_settings(self):
        """
        Load settings (from the registry on Windows)
        """

        q_settings = QtCore.QSettings()
        q_settings.beginGroup("view")

        # No need for toPoint, etc. : PySide converts types
        self.restoreGeometry(q_settings.value("main/geometry", self.saveGeometry()))
        self.restoreState(q_settings.value("main/saveState", self.saveState()))
        self.move(q_settings.value("main/pos", self.pos()))
        self.resize(q_settings.value("main/size", self.size()))
        q_settings.setValue("fullScreen", self.isFullScreen())

        q_settings.endGroup()

    def _save_view_settings(self):
        """
        Save settings (to the registry on Windows)
        """

        q_settings = QtCore.QSettings()
        q_settings.beginGroup("view")

        q_settings.setValue("main/geometry", self.saveGeometry())
        q_settings.setValue("main/saveState", self.saveState())
        q_settings.setValue("main/pos", self.pos())
        q_settings.setValue("main/size", self.size())
        q_settings.setValue("main/fullScreen", self.isFullScreen())

        q_settings.endGroup()

Using `isMaximized()`, I always get the application full screen.

**Comment by giumas** [comment]
Thank you for taking care of my question. I was working on Windows, and I was using the same approach coded here: https://gist.github.com/bootchk/5330231
but I believe that the part about `isMaximized()` has some portability issue.
 
If I change that part to: `if q_settings.value("fullScreen", self.isFullScreen()) == 'true':`, it works as expected on Windows. Is this portable?

**Comment by jdreaver** [comment]
I think that's portable. I use a similar approach on Windows and Linux.

**Comment by giumas** [comment]
Great! Thank you a lot
