### ISSUE TITLE
PySide in relocatable virtualenv: Library not loaded: @rpath/libpyside-python2.7.1.2.dylib

### ISSUE THREAD

**Issue by fredrikaverpil** [pyside/PySide#129]
I'm pip installing PySide into a virtualenv:

```
sudo virtualenv --always-copy $VENV
source $VENV/bin/activate
sudo $VENV/bin/pip install pyside
sudo $VENV/bin/python $VENV/bin/pyside_postinstall.py -install
deactivate
```

The virtualenv works great and I can run my Python/PySide script without problems:

```
$VENV/bin/python $SCRIPT
```

Now, I make my virtualenv relocatable: 

```
virtualenv --relocatable $VENV
```

I move it:

```
mv $VENV $VENV_RELOCATED
```

...and again run my script:

```
source $VENV_RELOCATED/bin/activate
$VENV_RELOCATED/bin/python $SCRIPT
```

This time around, I'm getting an error:

```
Traceback (most recent call last):
  File "script.py", line 1, in <module>
    from PySide import QtCore, QtGui, QtUiTools
ImportError: dlopen(/absolute/path/to/relocated_venv/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /absolute/path/to/relocated_venv/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found
```

These are the contents of the script:

```
from PySide import QtCore, QtGui, QtUiTools
```

Please note: the absolute path printed twice in the error message is the $VENV_RELOCATED

This is all on OS X 10.11.0 with Python 2.7.10 and PySide 1.2.2.

Any ideas on workaround so that the virtualenv could be moved around?

**Comment by fredrikaverpil** [comment]
I made a workaround which modifies a function in the pyside_postinstall.py script. If the script detect it is running inside of a virtualenv, it will not use `@rpath`. Instead it will use `@executable_path` and search relatively from the python binary in the virtualenv. Since the PySide module is always installed in the same place within a virtualenv, I thought this should work in all scenarios. I will now test this modification on Windows 10 and as well as on Ubuntu 14.04. But it works great so far on OS X 10.11 (El Capitan).

I don't know if you think this is a proper fix/workaround?

    def localize_libpaths(libpath, local_libs, enc_path=None):
        """ Set rpaths and install names to load local dynamic libs at run time

        Use ``install_name_tool`` to set relative install names in `libpath` (as
        named in `local_libs` to be relative to `enc_path`.  The default for
        `enc_path` is the directory containing `libpath`.

        Parameters
        ----------
        libpath : str
            path to library for which to set install names and rpaths
        local_libs : sequence of str
            library (install) names that should be considered relative paths
        enc_path : str, optional
            path that does or will contain the `libpath` library, and to which the
            `local_libs` are relative.  Defaults to current directory containing
            `libpath`.
        """
        if enc_path is None:
            enc_path = abspath(dirname(libpath))
        install_names = osx_get_install_names(libpath)
        need_rpath = False
        for install_name in install_names:
            if install_name[0] in '/@':
                continue
            if hasattr(sys, 'real_prefix'):
                # virtualenv detected - use @executable_path
                back_tick('install_name_tool -change %s @executable_path/../lib/python2.7/site-packages/PySide/%s %s' %
                   (install_name, install_name, libpath))
            else:
                # not a virtualenv - use @rpath
                back_tick('install_name_tool -change %s @rpath%s %s' %
                   (install_name, install_name, libpath))
                need_rpath = True
        if need_rpath and enc_path not in osx_get_rpaths(libpath):
            back_tick('install_name_tool -add_rpath %s %s' %
               (enc_path, libpath))

**Comment by ctismer** [comment]
Interesting, but did you use the latest version?
I mean, there is no version, the top has not yet been tagged, but that version does not have a pyside_postinstall.py any longer.
If you check out the top version and build pyside with `--ignore-git`, after applying your patch, then it makes sense to discuss it further.

Actually, I'm interested to use it on PySide2, that is the upcoming Qt5 version.

**Comment by ctismer** [comment]
Ah, you used version 1.2.2, because that for-loop from above has a bug, that I fixed in Pyide and PySide2.

**Comment by fredrikaverpil** [comment]
> If you check out the top version and build pyside with --ignore-git, after applying your patch, then it makes sense to discuss it further.

I'm not sure which version one you mean. Do you mean just downloading https://github.com/PySide/PySide/archive/master.zip and then build that?

**Comment by ctismer** [comment]
Oops, I just saw that I made a bad change, from the old gitorious submodules to github, but the modules were old ones from 2012. Will fix that, sorry

**Comment by fredrikaverpil** [comment]
Great, thanks. Let me know when it's ready. I'm calling this a day now :)

**Comment by fredrikaverpil** [comment]
By the way, I notice that another patch is needed to make PySide work properly in a relocatable virtualenv on Linux. I'm not sure if `patchelf` can be used to set something similar to @executable_path rather than setting rpath?

On Windows it all works as-is with no need for any patching.

**Comment by ctismer** [comment]
Ok, I think it is ready. Restored things with the help of PySide2. Then I had to search a while until I found out how to get rid of the Qt5 branches: I needed to also removed the tagging, then things finally vanished ;-)

**Comment by ctismer** [comment]
No idea about patchelf. I have to say that I always cared about OS X. Just since May, when I was forced to work with Windows and Linux on Qt5, but relocation was not my top priority.

If you find a nice solution, I'm happy to try a PR.

**Comment by fredrikaverpil** [comment]
I just compiled on both OS X and Linux and there's no need for any patching with this 1.3.0dev version of PySide. PySide works just fine even after having moved around the virtualenv. Awesome! :)

Is this 1.3.0dev version considered stable, or are you still fixing things and will release a true 1.3.0 later on?

**Comment by ctismer** [comment]
Fine to hear that, good that nothing was permanently damaged.
Actually, I did not want to do the final tagging, but was waiting for others who build the wheels, etc. And I guess this will just be 1.2.3, as the last Qt4 version. Then we will switch over to Qt5 (and this is a project that I first feared it would never start, and now I'm afraid it would never end), but that is still in alpha.

But maybe you motivated me to push it a bit ;-)

**Comment by fredrikaverpil** [comment]
Hehe, yeah. PySide is actually the standard in my line of work (visual effects for films/commercials/archviz) so lots of people are dependent on it even if it's in alpha :)

By the way, I was going to build from git on Windows 10, and I followed the [instructions](http://pyside.readthedocs.org/en/latest/building/windows.html). However, I got this:

	C:\Users\fredrik\Desktop\virtualenvs\pyside-setup>python.exe setup.py bdist_wheel --ignore-git --qmake=c:\Qt\4.8.6\bin\qmake.exe --openssl=c:\OpenSSL-Win64\bin --cmake="C:\Program Files (x86)\CMake\bin\cmake.exe"
	Removing C:\Users\fredrik\Desktop\virtualenvs\pyside-setup\pyside_package
	running bdist_wheel
	running build
	Python architecture is 64bit
	nmake not found. Trying to initialize the MSVC env...
	Searching MSVC compiler version 9.0
	error: Failed to find the MSVC compiler version 9.0 on your system.

The instructions doesn't say anything about Visual Studio 2008. Is it required?

**Comment by lck** [comment]
Only Windows sdk is required

R.
Dňa 3.10.2015 9:36 používateľ "Fredrik Averpil" <notifications@github.com>
napísal:

**Comment by fredrikaverpil** [comment]
> Only Windows sdk is required

I did install Windows SDK 7, but how do I define nmake when building?

Also, I'm on Windows 10. Maybe I need the Windows SDK 10?

**Comment by lck** [comment]
You can try to run the build from sdk command prompt
Dňa 3.10.2015 10:40 používateľ "Fredrik Averpil" <notifications@github.com>
napísal:

**Comment by ctismer** [comment]
@fredrikaverpil btw., why are you using PySide and not PyQt? They have changed their licensing. Would be interesting to know (I just like PySide for a reason).

**Comment by fredrikaverpil** [comment]
@lck ah, that's probably it. Thanks. Will try this when I'm at the machine. 

@ctismer actually, I don't have a preference. But since it's bundled with Autodesk's Maya and The Foundry's Nuke it works right out of the box in those applications.

**Comment by ctismer** [comment]
@fredrikaverpil interesting. That somehow closes the circle, because I also tried to learn why Autodesk insisted in PySide2 for Qt5. Some things simply persist, because of kinda virtual dependency. I like that.

**Comment by fredrikaverpil** [comment]
@ctismer I wonder if maybe Autodesk originally went with PySide because of licensing reasons. And now that they have a rather large user base with PySide scripts running in their software they may want to keep on going with PySide2... Are you working with them on PySide2?

**Comment by fredrikaverpil** [comment]
I can now also confirm that compile worked just fine in Windows too. I compiled for 64-bit and thus I needed Qt4 64-bit. Rather than building it myself from Qt4 v4.8.7, I used these [Qt v4.8.4 64-bit precompiled binaries](https://code.google.com/p/qt-msvc-installer/downloads/list) (qt-win64-opensource-4.8.4-noqt3-vs2008). Would you say this is wrong and that I should compile against Qt4 v4.8.7?

**Comment by ctismer** [comment]
> Would you say this is wrong and that I should compile against Qt4 v4.8.7?

No, I believe you are just fine with the pre-built build.

Yes, the issue will be closed with 1.2.3, if the others agree.

I guess the reluctance with tagging is that we than would have to build many binaries at once in no time, and that is always quite an undertaking. Should not be a problem with a build-bot. I think we will get one on PySide2.

**Comment by ctismer** [comment]
@fredrikaverpil I would like to get back to you with something in private emails.

**Comment by fredrikaverpil** [comment]
> Yes, the issue will be closed with 1.2.3, if the others agree.

Sounds great!

@ctismer sure, my email is fredrik.averpil@gmail.com

**Comment by lck** [comment]
Yes, 1.2.3 should be released soon.

**Comment by ctismer** [comment]
> I'm guessing that The Foundry also would like to have PySide2 bundled with Nuke since it comes with PySide today. Have you been in touch with The Foundry?

No, I have no idea what this is.

> By the way, will PySide2 be backwards-compatible with PySide?
Should these transitions also apply for when going from PySide to PySide2?

No, PySide2 is not backward compatible, and all the transitions apply. The transitions show only the tip of the iceberg - under the hood, the changes were even heavier, because PySide2 touches many internal things.

**Comment by duozmo** [comment]
Had this same issue with PySide 1.2.4. Installed via `pip` into an Anaconda [environment](http://conda.pydata.org/docs/using/envs.html), running on OS X 10.10.5 and Python 3.3. This came up while trying to use qt as a backend to matplotlib, though the line that triggers the error is basically the same as OP.

    $ ipython
    In [1]: %pylab qt
    
    ...
    /absolute/path/to/anaconda_environment/lib/python3.3/site-packages/matplotlib/backends/qt_compat.py in <module>()
    --> 126     from PySide import QtCore, QtGui, __version__, __version_info__
    ...
    
    ImportError: dlopen(/absolute/path/to/anaconda_environment/lib/python3.3/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside.cpython-33m.1.2.dylib
      Referenced from: /absolute/path/to/anaconda_environment/lib/python3.3/site-packages/PySide/QtCore.so
      Reason: image not found

If I [fix the dynamic library path](http://stackoverflow.com/a/25671015/134610):

    DYLD_LIBRARY_PATH=/absolute/path/to/anaconda_environment/lib/python3.3/site-packages/PySide/ ipython

Then the `%pylab qt` [magic](http://ipython.readthedocs.org/en/stable/interactive/magics.html#magic-pylab) loads just fine.

**Comment by techtonik** [comment]
@duozmo I'd recommend opening a new ticket to not lose the info.

**Comment by duozmo** [comment]
Can't reopen?

**Comment by techtonik** [comment]
@duozmo I can't.

**Comment by ctismer** [comment]
ok, opened it again

**Comment by ctismer** [comment]
@duozmo let's reduce the number of variables: Can you create a simple virtualenv for a regular python and check whether pip then also complains?
My idea is that it _might_ be an anaconda problem.

**Comment by fredrikaverpil** [comment]
I also have this issue with PySide 1.2.4.

```bash
Macdev:virtualenvs fredrik$ virtualenv --always-copy myenv
New python executable in myenv/bin/python2.7
Also creating executable in myenv/bin/python
Installing setuptools, pip, wheel...done.
Macdev:virtualenvs fredrik$ source myenv/bin/activate
(myenv)Macdev:virtualenvs fredrik$ pip install pyside
Collecting pyside
Installing collected packages: pyside
Successfully installed pyside-1.2.4
(myenv)Macdev:virtualenvs fredrik$ python
Python 2.7.10 (default, Nov  5 2015, 21:40:43) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.1.76)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PySide import QtCore, QtGui, QtUiTools
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Users/fredrik/virtualenvs/myenv/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /Users/fredrik/virtualenvs/myenv/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found
>>> 
```

**Comment by duozmo** [comment]
@ctismer Getting nearly an identical error in a simple virtualenv.

    >>> from PySide import QtCore
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: dlopen(/path/to/pysideenv/lib/python3.4/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside.cpython-34m.1.2.dylib
      Referenced from: /path/to/pysideenv/lib/python3.4/site-packages/PySide/QtCore.so
      Reason: image not found

That library is available, just apparently not where QtCore is looking:

    pysideenv $ find . -iname libpyside*
    ./lib/python3.4/site-packages/PySide/libpyside.cpython-34m.1.2.4.dylib
    ./lib/python3.4/site-packages/PySide/libpyside.cpython-34m.1.2.dylib
    ./lib/python3.4/site-packages/PySide/libpyside.cpython-34m.dylib

Certainly seems like something to do with `@rpath`. I'm sorry I don't have more time to investigate. I'm not really a PySide user, I just wanted to stop by to report the error.

**Comment by techtonik** [comment]
I suspect that Linux doesn't allow to load libraries from arbitrary paths.

**Comment by lck** [comment]
Is this not macos spesific problem ? i have tested pyside in relacatable
virtualenv on ubuntu mate without problems.
Dňa 8.11.2015 9:46 používateľ "anatoly techtonik" <notifications@github.com>
napísal:

**Comment by techtonik** [comment]
@lck I missed the OS X specifics, this issue need a flag that the bug is for OS X.

**Comment by fredrikaverpil** [comment]
Does anyone know of a workaround for this issue?

**Comment by fredrikaverpil** [comment]
As long as Qt4 is installed (`/usr/local/opt/qt/`), you can do this as workaround:

    export DYLD_LIBRARY_PATH=/Users/you/virtualenv/lib/python2.7/site-packages/PySide
    /Users/you/virtualenv/python

    dyld: warning, unknown environment variable: DYLD_LIBARY_PATH
    Python 2.7.10 (default, Jul 14 2015, 19:46:27) 
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> from PySide import QtCore
    >>> 

However, not very elegant.

**Comment by zzeleznick** [comment]
@fredrikaverpil This solved my problem, but I was seeking to run my PySide program from my root python environment. I might need to create a virtualenv for this specific purpose, as it now defaults my bash to start python immediately each time I open a tab or window.

**Comment by shellyan** [comment]
@duozmo  your method fixed my problem. my environment is  OS X 10.11.1 (15B42).

**Comment by AwwCookies** [comment]
@fredrikaverpil thanks, that solved my issue.

**Comment by fredrikaverpil** [comment]
@AwwCookies @shellyan @zzeleznick I would like to stress that I don't think this workaround is a proper one. You shouldn't need to set `DYLD_LIBRARY_PATH` to make PySide work in this scenario.

**Comment by sageeki** [comment]
Hi guys, I'm still looking for a solution that doesn't include a workaround. Any ideas? still not working even with PySide 1.2.4. Same error:

>>> from PySide import QtCore
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/Library/Python/2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: libpyside-python2.7.1.1.dylib
  Referenced from: /Library/Python/2.7/site-packages/PySide/QtCore.so
  Reason: unsafe use of relative rpath libpyside-python2.7.1.1.dylib in /Library/Python/2.7/site-packages/PySide/QtCore.so with restricted binary
>>>

**Comment by fredrikaverpil** [comment]
> Hi guys, I'm still looking for a solution

+1

**Comment by mangopipeline** [comment]
I'm having the same issue, i've applied the patch above and was able to get it working on my dev machine, but obviously it's not possible to run it of the network unless other machines have qt installed...
is there anyway to move the content of /usr/local/opt/qt/ to the virtualenv so that other machines don't have to do a brew install qt?
cheers,
Los

**Comment by sageeki** [comment]
So I ended up using Selenium with PhantomJS which is much better and
doesn't have issues with libraries.. I recommend you do the same!

-S.
ᐧ

**Comment by mangopipeline** [comment]
So the good news is that a built a new wheel using the latest from the git repository...
and everything seems to work great WITHOUT the need for the DYLD_LIBRARY_PATH 

Unfortunately like Fred i'm developing apps for VFX which is standardized in PySide, plus allot of my applications are already written and working on windows....

Fred, how are handling the qt frame work? do you know of away of moving those DLL's to the virtualenv?
can i move them to a folder and use some sort of environment variable to help pyside find them?

**Comment by fredrikaverpil** [comment]
> Fred, how are handling the qt frame work?

I'm not. I'm currently installing it locally on each machine that needs PySide. :angry:
This is of course not viable solution when you need to distribute your application to someone who does not have Qt installed locally.

You can build your own distribution of Qt from source and make the libraries load from within e.g. a virtualenv. The modifications needed to make the installation moveable is mostly about library loading. The build system wants to add an install path and you'll need to not do that. However, I've not had the time to do this even if this is one of the major gripes with distributing PySide applications in my opinion. But I understand it is doable.

**Comment by alexwidener** [comment]
Running into this on OSX 10.11.4 and I'm running in a simple virtualenv like the others.

**Comment by garrettr** [comment]
Running into this on OSX 10.10.5. This is a problem because the PySide [install docs](https://pyside.readthedocs.io/en/latest/installing/macosx.html) don't work if you're using a virtualenv, which is surprising.

```sh
$ brew install qt # stable 4.8.7
$ virtualenv env # defaults to 2.7.10 on Mac 10.10.5
$ . env/bin/activate
$ pip install -U PySide # ... takes a while
$ python -c 'from PySide import QtCore'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/garrett/code/deprecated-binaryninja-python/env/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /Users/garrett/code/deprecated-binaryninja-python/env/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found
```

Can confirm that the workaround from https://github.com/PySide/PySide/issues/129#issuecomment-158445160 works for me as well, but I also agreed that such a workaround should not be necessary.

**Comment by nfirvine** [comment]
I have this problem too, but I'm not in a virtualenv, just using a brew install'd python.

**Comment by theDrGray** [comment]
+1 not using a virtualenv 

Installed qt with brew and PySide 1.2.4 w pip. Getting the exact same:

`Library not loaded: @rpath/libpyside-python2.7.1.2.dylib`

Updating the DYLD_LIBRARY_PATH did not help.

**Comment by sspross** [comment]
same here on mac os x 10.11.6

**Comment by luizgarrido** [comment]
I think I solved the problem here... I don't need to install QT and even PySide on each machine anymore (Mac OS). I just have it in a central location and source from there. To do that I just had to fix once 11 linking problems using 'install_name_tool'

**Comment by mangopipeline** [comment]
Luiz,
For those of us, who don't have as much experience compiling in linux/OsX, can you give us a bit more detail on how you used "install_name_tool" to fix those linking problems?

It would be much appreciated :D

**Comment by luizgarrido** [comment]
Sure, I'm really busy today but I want to let you guys know what I did,
maybe it can help. I'll write in the weekend with more time.

**Comment by fredrikaverpil** [comment]
@luizgarrido much appreciated, looking forward to reading what you've been up to :)

**Comment by nall** [comment]
I didn't see an answer in this thread, so here's how I got PySide-1.2.4 working in a virtualenv on macOS Sierra. I'd installed qt via brew prior to this.

```
virtualenv venv
source venv/bin/activate
pip install PySide
install_name_tool -add_rpath `pwd`/venv/lib/python2.7/site-packages/PySide venv/lib/python2.7/site-packages/PySide/QtGui.so
install_name_tool -add_rpath `pwd`/venv/lib/python2.7/site-packages/PySide venv/lib/python2.7/site-packages/PySide/QtCore.so
```

**Comment by fredrikaverpil** [comment]
@nall nice, although that doesn't look like it offers relatability, right?

**Comment by fredrikaverpil** [comment]
In response to my previous post;

I haven't tested this myself (moved on to PySide2), but this could perhaps work:
```bash
# QtGui.so
install_name_tool -change QtGui.so @executable_path/../lib/python2.7/site-packages/PySide/QtGui.so venv/lib/python2.7/site-packages/PySide/QtGui.so
```

**Comment by fredrikaverpil** [comment]
Hm, I don't get the error anymore (I'm on El Capitan 10.11.6) and I can just use a relocatable venv out of the box:

```bash
# Check system-installed packages
$ pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
requests (2.12.1)
setuptools (28.8.0)
virtualenv (15.1.0)
wheel (0.29.0)

# Create "venv" virtualenv
$ virtualenv --always-copy venv
New python executable in /Users/fredrik/code/virtualenvs/venv/bin/python2.7
Also creating executable in /Users/fredrik/code/virtualenvs/venv/bin/python
Installing setuptools, pip, wheel...done.

# Check the packages of "venv"
$ venv/bin/pip list
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
pip (9.0.1)
setuptools (32.1.3)
wheel (0.29.0)

# Install PySide into "venv"
$ venv/bin/pip install pyside
Collecting pyside
Installing collected packages: pyside
Successfully installed pyside-1.2.4

# Attempt to import PySide (works fine)
$ venv/bin/python -c "from PySide import QtCore, QtGui, QtUiTools"

# Make virtualenv relocatable
$ virtualenv --relocatable venv
Making script /Users/fredrik/code/virtualenvs/venv/bin/easy_install relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/easy_install-2.7 relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/pip relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/pip2 relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/pip2.7 relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/pyside-uic relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/python-config relative
Making script /Users/fredrik/code/virtualenvs/venv/bin/wheel relative

# Move "venv"
$ mkdir some_new_path
$ mv venv some_new_path
$ cd some_new_path
$ mv venv moved_venv

# Attempt to import PySide in relocated virtualenv (works fine)
$ moved_venv/bin/python -c "from PySide import QtCore, QtGui, QtUiTools"
```
