### ISSUE TITLE
Unable to install on OS/X Yosemite 10.10.5 (Homebrew)

### ISSUE THREAD

**Issue by mpenkov** [PySide/PySide#131]
I followed the install instructions, but I'm getting this error:

```
Traceback (most recent call last):
  File "bar.py", line 18, in <module>
    import foo
  File "/Users/misha/webkit.py", line 1, in <module>
    from PySide.QtCore import QEventLoop, QTimer, QUrl
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/PySide/QtCore.so, 2): Library not loaded: @rpath/libpyside-python2.7.1.2.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/PySide/QtCore.so
  Reason: image not found
```

In the past, this appears to have been handled with `pyside_postinstall.py` but this script is no longer present:

```
bash-3.2$ pip show -f PySide | grep post
bash-3.2$ 
```

What am I doing wrong?

**Comment by fredrikaverpil** [comment]
I believe you are hitting the same issue as reported here: https://github.com/PySide/PySide/issues/129

**Comment by mpenkov** [comment]
@fredrikaverpil You're right. Setting 

    export DYLD_LIBRARY_PATH=/usr/local/lib/python2.7/site-packages/PySide

Solved the problem.

I didn't read the entire discussion you linked, but that was one of the proposed solutions.
