### ISSUE TITLE
PySide with zc.buildout can't use wheels

### ISSUE THREAD

**Issue by projekt01** [PySide/PySide#136]
PySide can't get installed without cmake using eggs. Can you please release windows 64 bit python eggs. Since we use zc.buildout which is not able to use wheels we can't install PySide without cmake installed.

**Comment by lck** [comment]
Windows eggs (32 and 64 bit) for all supported Python versions are now uploaded to https://download.qt-project.org/official_releases/pyside/.
Please note, that to install the packages you have to use the  --allow-all-external pip parameter, for example:
`c:\python34_64\Scripts\pip install -U pyside --allow-all-external`

**Comment by techtonik** [comment]
What about PySide2?
